version: "3.7"
services:
  my-cv-front-end:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-cv-front-end
    ports:
      - "3401:3401"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app/
    networks: 
      - my-cv-services
    command: ["npm","run","dev"]  
    
networks: 
  my-cv-services:
    external: true
    driver: bridge 
    
  